<?php

use yii\db\Schema;

class m140609_010314_populate_category_and_options_table extends \yii\db\Migration
{
    public function safeUp()
    {
        /*
        $this->batchInsert("{{%category}}", ["id", "name", "weight"],[
            [1, "recovery", 0],
            [2, "forgetting priorities", 2],
            [3, "anxiety", 4],
            [4, "speeding up", 6],
            [5, "ticked off", 8],
            [6, "exhausted", 10],
            [7, "relapse", 12]
        ]);
         */


        $this->batchInsert("{{%option}}", ["name", "category_id"],[
            ["no current secrets", 1],
            ["resolving problems", 1],
            ["identifying fears and feelings", 1],
            ["keeping commitments to meetings, prayer, family, church, people, goals, and self", 1],
            ["being open", 1],
            ["being honest", 1],
            ["making eye contact", 1],
            ["reaching out to others", 1],
            ["increasing in relationships with God and others", 1],
            ["accountability", 1],
            ["secrets", 2],
            ["bored", 2],
            ["less time/energy for God, meetings, and church", 2],
            ["avoiding support and accountability towards people", 2],
            ["superficial conversations", 2],
            ["sarcasm", 2],
            ["isolating yourself", 2],
            ["changes in goals", 2],
            ["flirting", 2],
            ["obsessed with relationships", 2],
            ["breaking promises/commitments", 2],
            ["neglecting family", 2],
            ["preoccupation with material things, television, or entertainment", 2],
            ["procrastination", 2],
            ["lying", 2], 
            ["over-confidence", 2],
            ["hiding money", 2],
            ["worry", 3],
            ["using profanity", 3], 
            ["being fearful", 3],
            ["being resentful", 3],
            ["replaying old, negative thoughts", 3],
            ["perfectionism", 3],
            ["juding others' motives", 3],
            ["makin goals and lists you can't complete", 3],
            ["poor planning", 3],
            ["mind reading", 3],
            ["fantasy", 3],
            ["masturbation", 3],
            ["pornography", 3],
            ["co-dependent rescuing", 3],
            ["sleep problems", 3],
            ["trouble concentrating", 3],
            ["seeking/creating drama", 3],
            ["gossip", 3],
            ["using over-the-counter medication for pain, sleep, and weight control", 3],
            ["super busy", 4],
            ["workaholic", 4],
            ["can't relax", 4],
            ["driving too fast", 4],
            ["avoiding slowing down", 4],
            ["feeling driven", 4],
            ["in a hurry", 4],
            ["can't turn off thoughts", 4],
            ["skipping meals", 4],
            ["binge eating (usually at night)", 4],
            ["overspending", 4],
            ["can't identify own feelings/needs", 4],
            ["repetitive, negative thoughts", 4],
            ["irritable", 4],
            ['making excuses for "having to do it all"', 4],
            ["dramatic mood swings", 4],
            ["lust", 4],
            ["too much caffeine", 4],
            ["over exercising", 4],
            ["nervousness", 4],
            ["difficulty being alone or with people", 4],
            ["difficulty listening to others", 4],
            ["avoiding support", 4],
            ["procrastinatino causing crises in money, work, or relationships", 5],
            ["sarcasm", 5],
            ["black and white, all or nothing thinking", 5],
            ["feeling that no one understands", 5],
            ["overreacting", 5],
            ["road rage", 5],
            ["constant resentments", 5],
            ["pushing others away", 5],
            ["increased isolation", 5],
            ["blaming", 5],
            ["self pity", 5],
            ["arguing", 5],
            ["rrationality", 5],
            ["can't handle criticism", 5],
            ["defensive", 5],
            ["people are avoiding you", 5],
            ["having to be right", 5],
            ["digestive problems", 5],
            ["headaches", 5],
            ["obsessive (stuck) thoughts", 5],
            ["can't forgive", 5],
            ["feeling grandiose (superior)", 5],
            ["intimidation", 5],
            ["feeling aggressive", 5],
            ["depressed", 6],
            ["panicked", 6],
            ["confused", 6],
            ["hopeless", 6],
            ["sleeping too much or too little", 6],
            ["can't cope", 6],
            ["overwhelmed", 6],
			['crying for "no reason"', 6],
			["can't think", 6],
			["forgetful", 6],
			["pessimistic", 6],
			["helpless", 6],
			["tired", 6],
			["numb", 6],
			["wanting to run", 6],
			["constant cravings for old coping behaviors", 6],
			["thinking of using drugs and alcohol", 6],
			["seeking out old unhealthy people and places", 6],
			["really isolated", 6],
			["people are angry with you", 6],
			["self-abuse", 6],
			["suicidal thoughts", 6],
			["no goals", 6],
			["survival mode", 6],
			["not returning phone calls", 6],
			["missing work", 6],
			["irritability", 6],
			["loss of appetite", 6],
			["returning to the place you swore you would never go again", 7],
			["giving up", 7],
			["giving in", 7],
			["out of control", 7],
			["lost in your addiction", 7],
			["lying to yourself and others", 7],
			["feeling you just can't manage without your coping behavior, at least for now", 7],
			["shame", 7],
			["condemnation", 7],
			["guilt", 7],
			["aloneness", 7]
       ]);
    }

    public function safeDown()
    {
        $this->delete("{{%option}}");
        $this->delete("{{%category}}");
    }
}
