#!/usr/bin/env php
<?php
/**
 * Yii test console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
defined('YII_ENV_TEST') or define('YII_ENV_TEST', true);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/aliases.php');

$config = yii\helpers\ArrayHelper::merge(
	require(__DIR__ . '/common/config/main.php'),
	require(__DIR__ . '/common/config/main-local.php'),
	require(__DIR__ . '/console/config/main.php'),
	require(__DIR__ . '/console/config/main-local.php'),
	require(__DIR__ . '/common/config/test.php'),
	require(__DIR__ . '/common/config/test-local.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
